spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/votacao
    username: votauser
    password: vota123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
server:
  port: 8080
